# (s) jdbc
datasource:
  default:
    password: '{cipher}AQCU17f7Qd66Uy4x4HkIL+hoUNy79up90emBqlxmpB0gS4KG8I1+XAiTsDR/ID/yzNV+jnNBOaYhzQiDACXPJBbHMlxLHE3k45UthgWqx1vjrlggO37gne3upkJvbbRSs8dUIFT8A7bA83UPzuEZNhEOeQfgTMEUnDVgvtFbEmA6ra9BQ0lT8ysu/EPjBKgXQh5G5K8DaqNfx/qS1M7zCmw28zursxOKYLn/2cVxG8WV8D/d7xFL4cUtloQp+zaDTd6tlJoQSGueAx0KxoAtkW+o7jhQWRvT3I8NyrsPDJKizHmqnuc6knGmUQ3oBnhMqkPyJDXw9KhS/On3pBXAb5bq5eIjkR6RdaokQ1/3/pt5ZY5QSNJD1sVhrWZsLAfoQzA='
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306
    username: '{cipher}AQCtG9jndjRXB61o9inAQU+jDz0Ug+7tu/KzpOe0fUPkeUxu3lBWgkXUhHOd3/YAgsyAOYuZxtE90WNFCkklbkcOXNeOug9J2bT82gA+dV5sgV97Kp9ui32gEZ/dG8nxqRG4b2Twmdb4LrF5TFfmLN20kPpRrPkXL62pPdzROBA9hHpWKRRRYA7WxjVS2yTQPMs9Z7V3Lnj48W3JMe85Y2cPHtAjJuKJ+YQB8AN/Ny/cUa3BXEqhmBW1npAva+/j9Hc7kvLs6TT+7dZ1XELH47nmUN+Ac/de149rYHh1sZmJxkTaFWd7PWru2+w0kpe+tewtOqMLKXsz4SD4n89B3JkfcfTY0sWtS/vyCeOH52ud0xb/43XGWV2Gor/MAgy67Wc='

# (e) jdbc

# (s) data-mongodb
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
# (e) data-mongodb


