# (s) jdbc
datasource:
    default:
        password: '{cipher}AQADDZ8BXL72JgHJTPoIgiAkK2nCcfItthEGthPHC2zN56T2Zt9VOCOv0x/hTCPQpQ5kZn02K7bYfRBzqQvPbMRocdkDeRGMqnv3/Ad2Xarf2bF1mMTk/XyrkHV/hZ4b1znTerl/Hafspjf5ByGIaZm7l/k8qX5nwC0fWR+UgEd5JeV/7YSbDefZDsI3Ipwp56oMmsPaLpfGHHSS+1KG+claCaLbdlpuwW2QMiPNwUN5i8dSIlcPubMEgfPax6WTgfAxHaBjIrNyIDpAjB+jvIj/6PoQiGI6n/5vuZGR5UnR6aEKJ8lywEnHXwBhe6BvccqKN/QkG5aOeKSNEXuHyVfQnyldYp8bgYFlJsto22Pc23LatNFWKGb7P5Z5ntTMnZg='
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mariadb://localhost:3306
        username: '{cipher}AQB5yP3DsYsfA5wV1RtX3P4XC51TEXc3qxVb0RWkOsaLhLa8k2n8OI2OeKgwEjhBQeOPyZ6L2iOzLYnSrHftgTPuTtWAY3fK9bXTXji0WrJH+WidDcRHGTYIknBX3YhkyOzhqKvnIFfZA/URuIiv9Dg1KWGC/jjrLEZGV2vgZrcuekzEaQU/1jiI0kfDLVdhNQ6VrVlnKXKQDVKUPOFSLONwG/qFdbGCVD7YFfpcq9tLt18dQlApdoJbYfEIvxSjJAJFMI+3U6iefuWdC+MO4ZqL0lYT5glWkpNdTr+is08icCuEG0OrB4TkGBjEYUZzNgZK3yTBzS+rU2TwPkSFVhQFNeWOj0oXlBzZosPit0fk7MTazV/gx7IYfxyRADzLy4I='

# (e) jdbc

# (s) data-mongodb
spring:
    data:
        mongodb:
            host: localhost
            port: 27017
# (e) data-mongodb


