# (s) jdbc
datasource:
  default:
    password: '{cipher}AQCU17f7Qd66Uy4x4HkIL+hoUNy79up90emBqlxmpB0gS4KG8I1+XAiTsDR/ID/yzNV+jnNBOaYhzQiDACXPJBbHMlxLHE3k45UthgWqx1vjrlggO37gne3upkJvbbRSs8dUIFT8A7bA83UPzuEZNhEOeQfgTMEUnDVgvtFbEmA6ra9BQ0lT8ysu/EPjBKgXQh5G5K8DaqNfx/qS1M7zCmw28zursxOKYLn/2cVxG8WV8D/d7xFL4cUtloQp+zaDTd6tlJoQSGueAx0KxoAtkW+o7jhQWRvT3I8NyrsPDJKizHmqnuc6knGmUQ3oBnhMqkPyJDXw9KhS/On3pBXAb5bq5eIjkR6RdaokQ1/3/pt5ZY5QSNJD1sVhrWZsLAfoQzA='
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306
    username: '{cipher}AQCU17f7Qd66Uy4x4HkIL+hoUNy79up90emBqlxmpB0gS4KG8I1+XAiTsDR/ID/yzNV+jnNBOaYhzQiDACXPJBbHMlxLHE3k45UthgWqx1vjrlggO37gne3upkJvbbRSs8dUIFT8A7bA83UPzuEZNhEOeQfgTMEUnDVgvtFbEmA6ra9BQ0lT8ysu/EPjBKgXQh5G5K8DaqNfx/qS1M7zCmw28zursxOKYLn/2cVxG8WV8D/d7xFL4cUtloQp+zaDTd6tlJoQSGueAx0KxoAtkW+o7jhQWRvT3I8NyrsPDJKizHmqnuc6knGmUQ3oBnhMqkPyJDXw9KhS/On3pBXAb5bq5eIjkR6RdaokQ1/3/pt5ZY5QSNJD1sVhrWZsLAfoQzA='

# (e) jdbc

# (s) data-mongodb
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
# (e) data-mongodb


